### ISSUE TITLE
Is aspirin support DKIM,SPF?

### ISSUE THREAD

**Issue by doggie1989** [masukomi/aspirin#12]

**Comment by nafg** [comment]
@masukomi ...?

**Comment by doggie1989** [comment]
@masukomi 
DKIM support will be nice...otherwise emails go to the junk box...

**Comment by doggie1989** [comment]
@nafg

**Comment by masukomi** [comment]
it does not. It specifically says this in the readme: 

> In most cases mail sent from Aspirin will not be accepted by a server implementing SPF mail authorization. This would be the case with ANY smtp server deployed on a user's desktop or any other machine not specified in the DNS record from corresponding to the "from" addresses host name.
