### ISSUE TITLE
Multiple To addresses causes slow sending

### ISSUE THREAD

**Issue by neilwightman** [masukomi/aspirin#4]
Hi.

I have a strange problem, if I create 2x messages with different to to addresses and send them with Aspirin they are sent very quickly. 

If I create 1 email with 2 people in the to list it always takes longer to send.

It appears the QueManager goes into a 1 minute sleep.
See the log message "There is no sendable item in the queue. Fallback to waiting state for a minute."

If I add more addresses it takes longer and longer.

Below is the log output.  There is no failed connection to the server, which I have seen with some email servers refusing connections if we send too many emails too fast.

<pre>
14:10:00,467 DEBUG Aspirin:77 - MailQue.service(): Remotely delivering mail javax.mail.internet.MimeMessage@1818f80
14:10:00,471  INFO Aspirin:136 - QueManager.run(): QueManager started.
14:10:00,472 TRACE Aspirin:289 - QuedItem (javax.mail.internet.MimeMessage@1818f80).isCompleted(): S0+F0/A2
14:10:00,472 TRACE Aspirin:179 - MailQue.getNextSendable(): Maintenance of MailQue - removed 0 items from 1
14:10:00,472 TRACE Aspirin:187 - MailQue.getNextSendable(): Found item to send. qi=QuedItem [id=javax.mail.internet.MimeMessage@1818f80; status=0; ]; 
14:10:00,472 DEBUG Aspirin:150 - QueManager.run(): Start delivery. qi=QuedItem [id=javax.mail.internet.MimeMessage@1818f80; status=1; ]; 
14:10:00,479 TRACE Aspirin:49 - GenericPoolableRemoteDeliveryFactory.makeObject(): New RemoteDelivery object created: RemoteDelivery-1
14:10:00,480 TRACE Aspirin:155 - QueManager.run(): Borrow RemoteDelivery object. rd=RemoteDelivery-1
14:10:00,480 TRACE Aspirin:156 - QueManager.run(): Pool state. A1/I0
14:10:00,481 TRACE Aspirin:677 - RemoteDelivery (RemoteDelivery-1).setQuedItem(): Item was set. qi=QuedItem [id=javax.mail.internet.MimeMessage@1818f80; status=1; ]; 
14:10:00,481 TRACE Aspirin:289 - QuedItem (javax.mail.internet.MimeMessage@1818f80).isCompleted(): S0+F0/A2
14:10:00,481 TRACE Aspirin:179 - MailQue.getNextSendable(): Maintenance of MailQue - removed 0 items from 1
14:10:00,481 TRACE Aspirin:178 - QueManager.run(): There is no sendable item in the queue. Fallback to waiting state for a minute.
14:10:00,481 TRACE Aspirin:585 - RemoteDelivery (RemoteDelivery-1).run(): Call delivering... qi=QuedItem [id=javax.mail.internet.MimeMessage@1818f80; status=1; ]; 
14:10:00,482 DEBUG Aspirin:170 - RemoteDelivery (RemoteDelivery-1).deliver(): Starting mail delivery. qi=QuedItem [id=javax.mail.internet.MimeMessage@1818f80; status=1; ]; 
14:10:00,586 TRACE Aspirin:231 - RemoteDelivery (RemoteDelivery-1).deliver(): 1 servers found for ptc.com.
14:10:00,586 DEBUG Aspirin:252 - RemoteDelivery (RemoteDelivery-1).deliver(): Attempting delivery of javax.mail.internet.MimeMessage@1818f80 to host smtp://int-mail.ptc.com to addresses [wmadm@ptc.com]
14:10:01,277 DEBUG Aspirin:309 - RemoteDelivery (RemoteDelivery-1).deliver(): Mail (javax.mail.internet.MimeMessage@1818f80) sent successfully to smtp://int-mail.ptc.com
14:10:01,278 TRACE Aspirin:289 - QuedItem (javax.mail.internet.MimeMessage@1818f80).isCompleted(): S1+F0/A2
14:10:01,278 TRACE Aspirin:289 - QuedItem (javax.mail.internet.MimeMessage@1818f80).isCompleted(): S1+F0/A2
14:10:01,278 TRACE Aspirin:206 - QuedItem.release(): Item released. qi=QuedItem [id=javax.mail.internet.MimeMessage@1818f80; status=0; ]; 
14:10:01,278 TRACE Aspirin:602 - RemoteDelivery (RemoteDelivery-1).run(): Release item. qi=QuedItem [id=javax.mail.internet.MimeMessage@1818f80; status=0; ]; 
14:10:01,278  INFO Aspirin:611 - RemoteDelivery (RemoteDelivery-1).run(): Try to give back RemoteDelivery object into the pool.
14:10:01,279 TRACE Aspirin:623 - RemoteDelivery (RemoteDelivery-1).run(): Wait for next sendable item.
14:11:00,484 TRACE Aspirin:289 - QuedItem (javax.mail.internet.MimeMessage@1818f80).isCompleted(): S1+F0/A2
14:11:00,484 TRACE Aspirin:179 - MailQue.getNextSendable(): Maintenance of MailQue - removed 0 items from 1
14:11:00,484 TRACE Aspirin:187 - MailQue.getNextSendable(): Found item to send. qi=QuedItem [id=javax.mail.internet.MimeMessage@1818f80; status=0; ]; 
14:11:00,484 DEBUG Aspirin:150 - QueManager.run(): Start delivery. qi=QuedItem [id=javax.mail.internet.MimeMessage@1818f80; status=1; ]; 
14:11:00,484 TRACE Aspirin:155 - QueManager.run(): Borrow RemoteDelivery object. rd=RemoteDelivery-1
14:11:00,485 TRACE Aspirin:156 - QueManager.run(): Pool state. A1/I0
14:11:00,485 TRACE Aspirin:677 - RemoteDelivery (RemoteDelivery-1).setQuedItem(): Item was set. qi=QuedItem [id=javax.mail.internet.MimeMessage@1818f80; status=1; ]; 
14:11:00,485 TRACE Aspirin:585 - RemoteDelivery (RemoteDelivery-1).run(): Call delivering... qi=QuedItem [id=javax.mail.internet.MimeMessage@1818f80; status=1; ]; 
14:11:00,485 TRACE Aspirin:289 - QuedItem (javax.mail.internet.MimeMessage@1818f80).isCompleted(): S1+F0/A2
14:11:00,485 DEBUG Aspirin:170 - RemoteDelivery (RemoteDelivery-1).deliver(): Starting mail delivery. qi=QuedItem [id=javax.mail.internet.MimeMessage@1818f80; status=1; ]; 
14:11:00,485 TRACE Aspirin:179 - MailQue.getNextSendable(): Maintenance of MailQue - removed 0 items from 1
14:11:00,488 TRACE Aspirin:178 - QueManager.run(): There is no sendable item in the queue. Fallback to waiting state for a minute.
14:11:00,488 TRACE Aspirin:231 - RemoteDelivery (RemoteDelivery-1).deliver(): 1 servers found for ptc.com.
14:11:00,488 DEBUG Aspirin:252 - RemoteDelivery (RemoteDelivery-1).deliver(): Attempting delivery of javax.mail.internet.MimeMessage@1818f80 to host smtp://int-mail.ptc.com to addresses [nwightman@ptc.com]
14:11:01,183 DEBUG Aspirin:309 - RemoteDelivery (RemoteDelivery-1).deliver(): Mail (javax.mail.internet.MimeMessage@1818f80) sent successfully to smtp://int-mail.ptc.com
14:11:01,183 TRACE Aspirin:289 - QuedItem (javax.mail.internet.MimeMessage@1818f80).isCompleted(): S2+F0/A2
14:11:01,183 TRACE Aspirin:289 - QuedItem (javax.mail.internet.MimeMessage@1818f80).isCompleted(): S2+F0/A2
14:11:01,184 TRACE Aspirin:206 - QuedItem.release(): Item released. qi=QuedItem [id=javax.mail.internet.MimeMessage@1818f80; status=3; ]; 
14:11:01,184 TRACE Aspirin:602 - RemoteDelivery (RemoteDelivery-1).run(): Release item. qi=QuedItem [id=javax.mail.internet.MimeMessage@1818f80; status=3; ]; 
14:11:01,184  INFO Aspirin:611 - RemoteDelivery (RemoteDelivery-1).run(): Try to give back RemoteDelivery object into the pool.
14:11:01,184 TRACE Aspirin:623 - RemoteDelivery (RemoteDelivery-1).run(): Wait for next sendable item.
</pre>

**Comment by lsolova** [comment]
Hello,

I know your problem, this caused by some definitions and solutions in RemoteDelivery. I am working on the next (refactored) release of delivery (which will support QoS too). If you could wait for a few weeks, the new release will resolve your problem.

Regards,
Laszlo

**Comment by lsolova** [comment]
Hello,

there is a beta of the new version in my fork, could you check it, please. In my opinion this will resolve your slow sending problem.

Regards,
Laszlo

**Comment by lsolova** [comment]
No response received, so it seems to me that the problem is resolved.
